style: github
template: CHANGELOG.tpl.md
tag_filter_pattern: '^v'
output: CHANGELOG.md
sections:
  - type: "feat"
    section: "âœ¨ Features"
  - type: "fix"
    section: "ğŸ› Bug Fixes"
  - type: "chore"
    section: "ğŸ”§ Maintenance"
  - type: "docs"
    section: "ğŸ“ Documentation"
  - type: "refactor"
    section: "ğŸ› ï¸ Refactoring"
  - type: "perf"
    section: "ğŸš€ Performance"
  - type: "test"
    section: "âœ… Testing"
